//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduGestor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignacione
    {
        public int AsignacionID { get; set; }
        public int CursoID { get; set; }
        public int UsuarioID { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public string NombreAsignacion { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
