//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduGestor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstudiantesGrupos
    {
        public int EstudianteID { get; set; }
        public int GrupoID { get; set; }
        public System.Guid IdentificadorUnico { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Grupos Grupos { get; set; }
    }
}
