//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduGestor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilUsuario
    {
        public int PerfilUsuarioID { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public string Departamento { get; set; }
        public Nullable<int> AnoMatricula { get; set; }
        public string Carrera { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
